//----------------------
// <auto-generated>
//    請勿修改此檔案內容，以免產生不可預期的錯誤。
//    產生日期:2025-03-14 01:41:00。
//    類別:外部起單, 表單:採購單, 版本:1
//     Generated using the NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Ede.Uofx.FormSchema.UofxFormSchema
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class FileItem
    {
        /// <summary>
        /// Id
        /// </summary>
        [Newtonsoft.Json.JsonProperty("Id", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Guid Id { get; set; }

        /// <summary>
        /// Name
        /// </summary>
        [Newtonsoft.Json.JsonProperty("FileName", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public string FileName { get; set; }


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class UofxFormSchemaFields
    {
        /// <summary>
        /// 採購單號
        /// </summary>
        [Newtonsoft.Json.JsonProperty("PurchaseID", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(255, MinimumLength = 1)]
        public string PurchaseID { get; set; }

        /// <summary>
        /// 供應商編號
        /// </summary>
        [Newtonsoft.Json.JsonProperty("SupplierID", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(255, MinimumLength = 1)]
        public string SupplierID { get; set; }

        /// <summary>
        /// 採購日期
        /// </summary>
        [Newtonsoft.Json.JsonProperty("PurchaseDate", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.DateTimeOffset PurchaseDate { get; set; }

        /// <summary>
        /// 採購類型，單選項目: 一般採購、緊急採購
        /// </summary>
        [Newtonsoft.Json.JsonProperty("PurchaseType", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public string PurchaseType { get; set; }

        /// <summary>
        /// 採購明細
        /// </summary>
        [Newtonsoft.Json.JsonProperty("PurchaseDetail", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<PurchaseDetailRow> PurchaseDetail { get; set; } = new System.Collections.ObjectModel.Collection<PurchaseDetailRow>();


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class PurchaseDetailRow
    {
        /// <summary>
        /// 採購明細編號
        /// </summary>
        [Newtonsoft.Json.JsonProperty("PurchaseDetailID", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(255, MinimumLength = 1)]
        public string PurchaseDetailID { get; set; }

        /// <summary>
        /// 產品編號
        /// </summary>
        [Newtonsoft.Json.JsonProperty("ProductID", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(255, MinimumLength = 1)]
        public string ProductID { get; set; }

        /// <summary>
        /// 數量
        /// </summary>
        [Newtonsoft.Json.JsonProperty("Quantity", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Range(1, 9999)]
        public int Quantity { get; set; }

        /// <summary>
        /// 單價
        /// </summary>
        [Newtonsoft.Json.JsonProperty("UnitPrice", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Range(1, 9999999)]
        public int UnitPrice { get; set; }


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class UofxFormSchema
    {
        /// <summary>
        /// 請勿修改
        /// </summary>
        [Newtonsoft.Json.JsonProperty("FormId", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Guid FormId { get; set; } = new System.Guid("ec442d75-aa78-4777-03a9-08dd61f6efce");

        /// <summary>
        /// 請勿修改
        /// </summary>
        [Newtonsoft.Json.JsonProperty("ScriptId", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Guid ScriptId { get; set; } = new System.Guid("d66c49c6-603d-422e-0434-08dd61f6efce");

        /// <summary>
        /// 人員帳號
        /// </summary>
        [Newtonsoft.Json.JsonProperty("Account", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public string Account { get; set; }

        /// <summary>
        /// 申請者原公司代碼(如為其他公司兼職才需要填)
        /// </summary>
        [Newtonsoft.Json.JsonProperty("CorpCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string CorpCode { get; set; }

        /// <summary>
        /// 部門代碼，此人員所屬的部門
        /// </summary>
        [Newtonsoft.Json.JsonProperty("DeptCode", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public string DeptCode { get; set; }

        /// <summary>
        /// 起單完成要回覆的 api url
        /// </summary>
        [Newtonsoft.Json.JsonProperty("CallBackUrl", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string CallBackUrl { get; set; }

        /// <summary>
        /// 使用者自訂資料，會在 CallBack 時回傳
        /// </summary>
        [Newtonsoft.Json.JsonProperty("CustomData", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string CustomData { get; set; }

        /// <summary>
        /// 急件
        /// </summary>
        [Newtonsoft.Json.JsonProperty("Urgent", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool Urgent { get; set; }

        /// <summary>
        /// 備註說明
        /// </summary>
        [Newtonsoft.Json.JsonProperty("Opinion", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Opinion { get; set; }

        /// <summary>
        /// 附件。請先呼叫檔案上傳 (UofxService.File.FileUpload) 取得 id 和 name
        /// </summary>
        [Newtonsoft.Json.JsonProperty("AttachFiles", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<FileItem> AttachFiles { get; set; }

        /// <summary>
        /// 表單欄位
        /// </summary>
        [Newtonsoft.Json.JsonProperty("Fields", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public UofxFormSchemaFields Fields { get; set; } = new UofxFormSchemaFields();


    }
}